theme-metaodi:
    use: "theme"

bower_components:
    use: "static"

production_url: 'https://metaodi.ch'

date_format: '%d.%m.%Y'

posts:
    sort: ["date", "desc"]
    rss:
        enable: true 
        limit: 1000
    paginator:
        per_page: 10

widgets:
    google_prettify:
        linenums : true
        cdn:
            enable: true
            path: "https://cdnjs.cloudflare.com/ajax/libs/prettify/188.0.0/prettify.js"
    analytics:
        use: google
        tracking_id : 'UA-47578431-1'
    comments:
        use : disqus
        short_name : metaodi
