"theme-metaodi":
    "use": "theme"

"bower_components":
    "use": "static"

"date_format": '%d.%m.%Y'

"posts":
    "sort": ["date", "desc"]
    rss:
        enable: true 
        limit: 1000
    paginator:
        per_page: 10

widgets:
    analytics:
        use: google
        tracking_id : 'UA-47578431-1'
